jobs:
  - name: pipelines-demo-manifest
    type: manifest
    steps:
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image
     - TASK: managed

  - name: deploy-pipelines-demo
    type: deploy
    steps:
      - IN: pipelines-demo-manifest
      - IN: docker-options
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: upgrade

  - name: runSh
    type: runSh
    steps:
      - IN: pipelines-demo-manifest
      - TASK:
        - script: echo 'This block executes when the TASK starts'

  - name: runSh2
    type: runSh
    steps:
      - IN: pipelines-demo-manifest
      - TASK:
        - script: echo 'This block executes when the TASK starts'

