jobs:
  - name: pipelines-demo-manifest
    type: manifest
    steps:
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed
    on_success:
     - NOTIFY: irc
        

  - name: deploy-pipelines-demo
    type: deploy
    flags:
      - job-flag
    steps:
      - IN: pipelines-demo-manifest
      - IN: docker-options
      - IN: ecs-cluster
      - IN: replicas
      - TASK: managed
        deployMethod: upgrade

  - name: runSh
    type: runSh
    steps:
      - IN: pipelines-demo-manifest
      - IN: rsync_test_gitRepo
      - TASK:
        - script: echo 'This block executes when the TASK starts'
        - script: sleep 1


  - name: runSh3
    type: runSh
    steps:
      - IN: deploy-pipelines-demo
      - TASK:
        - script: echo 'This block executes when the TASK starts'
